config/routes.rb
Rails.application.routes.draw do
  get 'favorites/favorite'
  devise_for :users

  authenticated :user do
    root to: 'puppies#index', as: :authenticated_root
  end
  root to: 'home#index'

  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/enquire', to: 'puppies#enquire', as: 'enquire'
  post '/enquire', to: 'puppies#email'
  get 'home/favorite'
  post '/contact', to: 'home#email'
  resources :puppies do
    put :favorite, on: :member
  end
end

app/models/application_record.rb
# Rubo cop needs a comment here
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :puppies
end

app/models/favorite_puppy.rb
#  For our favorite puppy
class FavoritePuppy < ApplicationRecord
  belongs_to :user
  belongs_to :puppy
end

app/models/image_uploader.rb
# Used for shrine
class ImageUploader < Shrine
  # plugins and uploading logic
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  geocoded_by :full_address
  after_validation :geocode


  def full_address
    "7 kelly street, 2007, Australia"
  end
end

app/models/puppy.rb
# Handles our puppies
class Puppy < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user

  # Favorited by users
  has_many :favorite_puppies # just the 'relationships'
  has_many :favorited_by, through: :favorite_puppies, source: :user #

  # very ugly sql search function
  def self.search(search)
    where('name ILIKE ? OR breed ILIKE ? OR age ILIKE ? OR size ILIKE ? OR gender ILIKE ? OR bio ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
# Made by Devise to handle our login
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :puppies
  has_one :location

  # Favorite puppies of user
  has_many :favorite_puppies # just the 'relationships'
  has_many :favorites, through: :favorite_puppies, source: :puppy # the actual puppies a user favorites

  def add_favorite(puppy)
    if self.favorites.where(id: puppy.id).empty?
      FavoritePuppy.create(user: self, puppy: puppy)
    end
  end
end

app/controllers/application_controller.rb
# Rubo cop needs a comment here
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
# This handles our favourite controls
class FavoritesController < ApplicationController
  def favorite
    # Add and remove favorite puppies
    # for current_user
    type = params[:type]
    if type == 'favorite'
      current_user.favorites << @puppy
      redirect_to :back, notice: "You favorited #{@puppy.name}"

    elsif type == 'unfavorite'
      current_user.favorites.delete(@puppy)
      redirect_to :back, notice: "Unfavorited #{@puppy.name}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
end

app/controllers/home_controller.rb
# Rubo cop needs a comment here
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:contact]
  def index; end

  def favorite; end

  def contact
    @location = Location.new(id: 1, address: "7 kelly street", city: "sydney", postcode: "2007", country: "Australia", latitude: -33.881959, longitude: 151.195238, user_id: 1)
  end

  def email
    email = current_user.email
    contact_name = params[:name]
    message = params[:message]
    ContactMailer.send_contact_email(email, contact_name, message).deliver_now
    redirect_to root_path
  end
end

app/controllers/puppies_controller.rb
# This takes care of our puppies project
class PuppiesController < ApplicationController
  before_action :authenticate_user!, only: [:enquire]
  before_action :set_puppy, only: %i[show edit update destroy]

  # GET /puppies
  # GET /puppies.json
  def index
    @puppies = Puppy.all

    # adding conditions to find puppies if given search params
    @puppies = if params[:search]
                 Puppy.search(params[:search]).order('created_at DESC')
               else
                 Puppy.all.order('created_at DESC')
               end
  end

  # GET /puppies/1
  # GET /puppies/1.json
  def show; end

  # GET /puppies/new
  def new
    @puppy = Puppy.new
  end

  # GET /puppies/1/edit
  def edit; end

  # POST /puppies
  # POST /puppies.json
  def create
    @puppy = Puppy.new(puppy_params)

    respond_to do |format|
      if @puppy.save
        format.html { redirect_to @puppy, notice: 'Puppy was successfully created.' }
        format.json { render :show, status: :created, location: @puppy }
      else
        format.html { render :new }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # Add and remove favorite puppies
  # for current_user
  def favorite
    type = params[:type]
    if type == 'favorite'
      current_user.favorites << @puppy
      redirect_to :back, notice: "You favorited #{@puppy.name}"

    elsif type == 'unfavorite'
      current_user.favorites.delete(@puppy)
      redirect_to :back, notice: "Unfavorited #{@puppy.name}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  def enquire; end

  def email
    email = current_user.email
    contact_name = params[:name]
    message = params[:message]
    ContactMailer.send_contact_email(email, contact_name, message).deliver_now
    redirect_to root_path
  end

  # PATCH/PUT /puppies/1
  # PATCH/PUT /puppies/1.json
  def update
    respond_to do |format|
      if @puppy.update(puppy_params)
        format.html { redirect_to @puppy, notice: 'Puppy was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppy }
      else
        format.html { render :edit }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.json
  def destroy
    @puppy.destroy
    respond_to do |format|
      format.html { redirect_to puppies_url, notice: 'Puppy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_puppy
    @puppy = Puppy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def puppy_params
    params.require(:puppy).permit(:image, :name, :age, :breed, :size, :gender, :bio, :desexed, :vaccinated, :adoption_fee)
  end
end

app/helpers/application_helper.rb
# Rubocop needs a comment here
module ApplicationHelper
end

app/helpers/favorites_helper.rb
# Rubocop likes comments here
module FavoritesHelper
end

app/helpers/home_helper.rb
# Rubo cop needs a comment here
module HomeHelper
end

app/helpers/puppies_helper.rb
# Rubo cop needs a comment here
module PuppiesHelper
end

app/views/favorites/favorite.html.erb
<h1>Favorites#favorite</h1>
<p>Find me in app/views/favorites/favorite.html.erb</p>

app/views/home/about.html.erb
<div class="row align-items-center">
<div class="col-md-8 mx-auto">
<h2 class="center">ABOUT</h2></br>
  <div class="text-black center">
  <p>Pawesome was founded in 2017 by Travis, James and Carmen. </p></br>
  <p>Its mission is to save and rescue abandoned dogs and puppies in NSW, Australia. Many of these animals are family pets that have been abandoned and left to fend for themselves on the streets. </p></br>
  <p>We believe that every dog deserves a chance at life.</p>
  </div>
</div>
  <div class="row">
    <div class="col-4">
          <%= image_tag('travisdog-min.jpeg', class: ' img-fluid rounded') %>
          Travis
    </div>
    <div class="col-4">
        <%= image_tag('Carmendog-min.jpeg', class: 'aboutdog img-fluid rounded') %>
        Carmen
    </div>
    <div class="col-4">
      <%= image_tag('jamesdog-min.jpeg', class: ' img-fluid rounded') %>
      James
    </div>

  </div>
</div>

app/views/home/contact.html.erb
<div class="row align-items-center">
<div class="col-md-10 mx-auto">
<h2 class="center">CONTACT</h2></br>
  <div class="text-black center">
  <p>At Pawesome, we are always happy to hear from you. Please use the form below to contact us.</p>

  <%= form_with(model: @contact, method: :post) do |form|%>
  <div class="form-group">
  <%= form.text_field :name, placeholder: 'Name' %>
  </div>
  <div class="form-group">
      <p class="form-control-static"><%= current_user.email %></p>
  </div>
  <div class="form-group">
  <%= form.text_area :message, placeholder: 'Enter message', class: 'forms' %>
  </div>
  <%= form.submit 'Submit', class: 'btn' %>
  <% end %>
  <br><p>Alternatively, we can be found at 7 Kelly Street, Ultimo.</p></br>
  </div>
  <div>
    <iframe src = "https://maps.google.com/maps?q=<%= @location.latitude %>,<%= @location.longitude %>&hl=es;z=14&amp;output=embed" class = "map" ></iframe>
  </div>
</div>
</div>

app/views/home/favorite.html.erb
<h1>Home#favorite</h1>
<p>Find me in app/views/home/favorite.html.erb</p>

app/views/home/index.html.erb
<div class="container banner-wrap">
	<%= image_tag('puppy-for-adoption-min.jpg', class: 'banner') %>
	<%= button_to 'Browse Dogs', puppies_path, :method => :get, class: 'btn-lg btn-browse' %>
</div>

app/views/layouts/_nav.html.erb
<div class="container-fluid">
	<nav class="navbar sticky-top navbar-expand-md navbar-default">

		<!--Holds logo and menu button  -->
		<div class="navrow">
			<!-- main logo  -->
			<%= link_to image_tag('logo.png', class: "logo"), root_path %>

			<!-- Menu button -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false">
				<span class="glyphicon btnnav btn-sm">Menu</span>
			</button>
		</div>

		<!--Menu items  -->
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav">

				<!--About  -->
				<li class="nav-item navtext text-center"><%= link_to "About", about_path, class: 'text-black nav-link' %></li>

				<!--Browse Dogs  -->
				<li class="nav-item navtext text-center"><%= link_to "Browse Dogs", puppies_path, class: 'text-black nav-link' %></li>

				<!--Contact us  -->
				<li class="nav-item navtext text-center"><%= link_to "Contact Us", contact_path, class: 'text-black nav-link text-center' %></li>

				<!-- if they aren't signed in show signin and register  -->
				<% if (!user_signed_in?) %>

				<li class="nav-item navtext text-center"><%= link_to "Login", new_user_session_path, class: 'text-black nav-link' %></li>

				<li class="nav-item navtext text-center"><%= link_to "Register", new_user_registration_path, class: 'text-black nav-link' %></li>

			<% else %>
				<!-- If they are show profile and Signout  -->
				<!--profile  -->
				<li class="nav-item"><%= link_to image_tag('profile.svg'), edit_user_registration_path , class: 'text-black text-center nav-link' %></li>
				<!--Signout  -->
				<li class="nav-item"><%= link_to image_tag('logout.svg'), destroy_user_session_path, method: :delete, class: 'text-black text-center nav-link' %></li>

			</ul>
			<% end %>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawesome</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">

  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'shared/message' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/puppies/_form.html.erb
<div class="container">
  <div class="row align-items-center">
  <div class="col-md-4 mx-auto">

<%= form_with(model: puppy, local: true) do |form| %>
  <% if puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% puppy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row center text-black">
  <div class="field">
    <br>
    <%= form.file_field :image, id: :puppy_image, class: "form-control" %>
    </br>
  </div>
  </div>

  <div class="form-group">
    <p><%= form.text_field :name, id: :puppy_name, placeholder: 'Dog name', class: "form-control" %></p>
  </div>

  <div class="form-group">
    <p><%= form.text_field :age, id: :puppy_age, placeholder: 'Age', class: "form-control" %></p>
  </div>

  <div class="form-group">
    <%= form.text_field :breed, id: :puppy_breed, placeholder: 'Breed', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :size, id: :puppy_size, placeholder: 'Size', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :gender, id: :puppy_gender, placeholder: 'Gender', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_area :bio, id: :puppy_bio, placeholder: 'Bio', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :adoption_fee, id: :puppy_adoption_fee, placeholder: 'Adoption Fee', class: "form-control" %>
  </div>

  <div class="field center">
    <%= form.label :desexed %>
    <%= form.check_box :desexed, id: :puppy_desexed %>
    <%= form.label :vaccinated %>
    <%= form.check_box :vaccinated, id: :puppy_vaccinated %>
  </div>

  <div class="actions center">
    <%= form.submit class: 'btn' %>
  </div>

<% end %>
</div>
</div>
</div>

app/views/puppies/edit.html.erb
<div class="row center">
<h2 class="center"> EDIT DOG PROFILE</h1>

<%= render 'form', puppy: @puppy %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

app/views/puppies/enquire.html.erb
<div class="row align-items-center">
  <div class="col-md-10 mx-auto">
    <h2 class="center">Want to adopt this pet?</h2></br>
    <div class="text-black center">
      <form class="form-horizontal">
        <%= form_with(model: @contact, method: :post) do |form|%>
        <div class="form-group">
        <%= form.text_field :name, placeholder: 'Name' %>
        </div>
        <div class="form-group">
            <p class="form-control-static"><%= current_user.email %></p>
        </div>
        <p>We recommend sharing some basic information about you and your lifestyle to help the Pawesome Adoption Group assist you with your pet enquiry. For example: I have children under 5; I have a dog/cat/other pets; I work part time/full-time etc. The more information you provide in your message, the more likely you are to receive a response.</p>
        <div class="form-group">
        <%= form.text_area :message, placeholder: 'Enter message', class: 'forms' %>
        </div>
        <%= form.submit 'Send Enquiry', method: :post, class: 'btn' %>
        <% end %>
      </form>
    </div>
  </div>
</div>

app/views/puppies/index.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-3">
			<div class="row center">
				<h2>FIND A PUP</h2>
			</br>
		</div>
		<div class="row center">
			<!--Search box -->
			<%= form_tag(puppies_path, :method => "get") do %>
			<br><%= text_field_tag :search, params[:search], placeholder: "      Find a Pawmate"%></br>
			<br><%= submit_tag "FETCH", class: 'btn' %></br>
			<% end %>
		</div>
	</div>

<div class="col-md-9">
    <div class="row center">
      <p><h2>AVAILABLE DOGS</h2></p>
      </br>
    </div>
    <div class="row center">
    <% @puppies.each do |puppy| %>
      <div class="col-md-6">
      <div class="card">
      </br>
      <%= link_to image_tag(puppy.image_url, class: 'profileindex'), puppy_path(puppy.id) %>
      <div class="card-body">
        <h4 class="card-title center"><%= puppy.name %></h4>
        <p class="text-black center">
          Age: <%= puppy.age %>
          </br>
          Gender: <%= puppy.gender %>
          </br>
          Breed: <%= puppy.breed %>
          </br></br>
          <%= link_to "ENQUIRE", enquire_path, class: "btn center" %>
          </br>
      </div>
      </div>
      </div>
    <% end %>

    <% if current_user.present? && current_user.email == 'admin@pawesome.com' %>
        <div>
        <%= link_to 'New Puppy', new_puppy_path, class: 'btn center' %>
        </div>
    <% else %>
    <% end %>
  </div>

</div>
</div>
</div>

app/views/puppies/new.html.erb
<div class="container">
<div class="row center">
<h2 class="center"> NEW DOG PROFILE </h2>
<%= render 'form', puppy: @puppy %>

<%= link_to 'Back', puppies_path %>

app/views/puppies/show.html.erb
<div class="container">
  <div class="row center">
    </br><div><%= image_tag @puppy.image_url, class: 'profile' %></div></br>
  </div>
</div>
<section class="flex-wrapper">
<div class="wrap_left">
  <h1 class="puppyname">
  <%= @puppy.name %>
  </h1>
<div><p><%= @puppy.bio %></p></div>
<h2>Adoption Details</h2>
<div>
<p>Please Contact: Pawesome through the link below </p>

<%= button_to "ENQUIRE", enquire_path, method: :get, class: "btn" %>

<p>For more information about the Pawesome Adoption program visit <a target="_blank" href="https://github.com/Travz08/hackathon-term2">https://github.com/Travz08/hackathon-term2</a></p>
</div>
</div>
<div class="wrap_right">
<dl>
<dt>Location:</dt>
<dd>New South Wales</dd>
</dl>

<dl>
<dt>Age:</dt>
<dd><%= @puppy.age %></dd>
<dt>Gender:</dt>
<dd><%= @puppy.gender %></dd>
<dt>Breed:</dt>
<dd><%= @puppy.breed %></dd>
<dt>Size:</dt>
<dd><%= @puppy.size %></dd>
<dt>Adoption fee:</dt>
<dd>$<%= @puppy.adoption_fee %></dd>
<dt>Desexed:</dt>
<dd><% if @puppy.desexed == true %>Yes<% else %>No<% end %></dd>
<dt>Vaccinated:</dt>
<dd><% if @puppy.vaccinated == true %>Yes<% else %>No<% end %></dd>
</dl>

</div>
</section>
<%= link_to 'Back', puppies_path, class: "btn" %>

<% if current_user.present? && current_user.email == 'admin@pawesome.com' %>
    <%= link_to 'Edit', edit_puppy_path(@puppy), class: "btn" %>
    <%= link_to 'Destroy', @puppy, method: :delete, class: "btn", data: { confirm: 'Are you sure?' } %>
<% else %>
<% end %>

app/views/shared/_devisemessage.html.erb
<% unless resource.errors.empty? %>
  <script type= "text/javascript">
  <% resource.errors.full_messages.each do |value| %>
    toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type= "text/javascript">
  <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>